# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81c317de457ed7895fbb8158687047eaaee5852afdec6c78e362f99df773fc873da44f646584f6b164747620abb337db60248945637f12ade7259e44e4b7875

test:
  secret_key_base: 4748b0740eedc979cee9513cf329150c41ed46a0fad534c8e17cda5969bea6d2f3b0c356029833d0ab58fdb00fe57973a3d80ba8a3a6b18ea4ad157c30f40e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
